### ISSUE TITLE
Meta: Project/Paper submission

### ISSUE THREAD

**Issue by jeremiastraub** [ThorstenBuss/CQD#5]
Here, we can collect everything that has to be done for handing in the project-paper. Feel free to add stuff, change the structure, tick completed tasks, ...

### To-Do:

- [x] Implemented Fourier Split-Step method
- [x] Implemented 1D case
  - [x] Solitons
- [x] Implemented 2d case
  - [x] Solitons
  - [x] Vortices
  - ~~[ ] Added initialization patterns (collection of initial states that are used for the project-paper)~~ (just commented out in the code if necessary)
- [x] __Code is well documented and cleaned-up__
  - [x] solitons1d
  - [x] solitons2d
  - [x] vortices2d
- [x] __Paper__
  - [x] Introduction
  - [x] Theory
  - [x] (Methods) Split-step fourier
  - [x] results
    - [x] solitons 1D
    - [x] solitons 2D
    - [x] vortices2D
  - [x] summary
  - [x] uploaded to the repo
- [x] __README__ includes movies, short description and link to the report

### Remarks:
* ...
